CREATE TABLE IF NOT EXISTS Users (
    UserId INTEGER PRIMARY KEY NOT NULL,
    UserName TEXT NOT NULL

);

CREATE TABLE IF NOT EXISTS Temperatures (
    TemperatureId INTEGER PRIMARY KEY NOT NULL,
    UserId INTEGER NOT NULL,
    TemperatureTimestamp DATETIME NOT NULL,
    Temperature REAL NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(UserId)
);